name: Simple commands
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run:  echo "Hello, World!"

      - name: show Date
        run: Date

      - name: List Files
        run: ls -la